# Generated by Django 5.2.3 on 2025-07-07 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('REDUCIR_GASTO', 'Reducir Gasto'), ('OPTIMIZAR_CATEGORIA', 'Optimizar Categoría'), ('PATRON_TEMPORAL', 'Patrón Temporal'), ('META_AHORRO', 'Meta de Ahorro'), ('ALERTA_LIMITE', 'Alerta de Límite'), ('HABITO_FINANCIERO', 'Hábito Financiero'), ('COMPARATIVA', 'Comparativa con Promedio')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recomendación',
                'verbose_name_plural': 'Tipos de Recomendación',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionGenerada',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje de Recomendación')),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Actual')),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Objetivo')),
                ('ahorro_potencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ahorro Potencial')),
                ('porcentaje_impacto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Impacto')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Generación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('vista', models.BooleanField(default=False, verbose_name='Vista por el Usuario')),
                ('aplicada', models.BooleanField(default=False, verbose_name='Aplicada por el Usuario')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('periodo_analisis_dias', models.IntegerField(default=30, verbose_name='Período de Análisis (días)')),
                ('confianza_algoritmo', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Confianza del Algoritmo (%)')),
                ('categoria_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.tipogasto', verbose_name='Categoría Relacionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendaciones.tiporecomendacion', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Recomendación Generada',
                'verbose_name_plural': 'Recomendaciones Generadas',
                'ordering': ['-fecha_generacion', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaComparativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_sistema', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Promedio del Sistema')),
                ('mediana_sistema', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mediana del Sistema')),
                ('percentil_25', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentil 25')),
                ('percentil_75', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentil 75')),
                ('percentil_90', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentil 90')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cálculo')),
                ('usuarios_en_muestra', models.IntegerField(verbose_name='Usuarios en Muestra')),
                ('periodo_meses', models.IntegerField(default=3, verbose_name='Período (meses)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.tipogasto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Estadística Comparativa',
                'verbose_name_plural': 'Estadísticas Comparativas',
                'ordering': ['-fecha_calculo'],
                'unique_together': {('categoria', 'periodo_meses')},
            },
        ),
        migrations.CreateModel(
            name='PatronUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_promedio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gasto Promedio Mensual')),
                ('gasto_maximo_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gasto Máximo Mensual')),
                ('gasto_minimo_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gasto Mínimo Mensual')),
                ('transacciones_promedio_mes', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Transacciones Promedio/Mes')),
                ('dia_semana_mas_gasto', models.IntegerField(blank=True, null=True, verbose_name='Día de Semana con Más Gasto')),
                ('hora_mas_frecuente', models.IntegerField(blank=True, null=True, verbose_name='Hora Más Frecuente')),
                ('tendencia_crecimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tendencia de Crecimiento (%)')),
                ('volatilidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Volatilidad')),
                ('porcentaje_vs_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% vs Total de Gastos')),
                ('ranking_importancia', models.IntegerField(verbose_name='Ranking de Importancia')),
                ('fecha_ultimo_analisis', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Último Análisis')),
                ('periodo_analisis_meses', models.IntegerField(default=3, verbose_name='Período de Análisis (meses)')),
                ('confiabilidad_datos', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Confiabilidad de Datos (%)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.tipogasto', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Patrón de Usuario',
                'verbose_name_plural': 'Patrones de Usuario',
                'ordering': ['ranking_importancia'],
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
