# Generated by Django 5.2.3 on 2025-07-02 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Máximo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.tipogasto', verbose_name='Categoría')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('categoria', 'id_usuario', 'fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.CreateModel(
            name='AlertaPresupuesto',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('CERCA_LIMITE', 'Cerca del límite'), ('LIMITE_EXCEDIDO', 'Límite excedido'), ('ADVERTENCIA', 'Advertencia general')], max_length=20, verbose_name='Tipo de Alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje de Alerta')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('vista', models.BooleanField(default=False, verbose_name='Vista')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Alerta de Presupuesto',
                'verbose_name_plural': 'Alertas de Presupuesto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
