# Generated by Django 5.2.3 on 2025-07-13 16:14

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Sube una imagen para tu foto de perfil (máximo 5MB)', null=True, upload_to=authentication.models.usuario_foto_path, verbose_name='Foto de Perfil'),
        ),
    ]
