# Generated by Django 5.2.3 on 2025-07-06 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usuario_foto_perfil_alter_usuario_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 6 dígitos para verificación', max_length=6, verbose_name='Código de Verificación')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Recuperación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usado', models.BooleanField(default=False, verbose_name='Token Usado')),
                ('intentos', models.IntegerField(default=0, verbose_name='Intentos de Verificación')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['codigo', 'usado'], name='authenticat_codigo_fd894a_idx'), models.Index(fields=['usuario', 'usado'], name='authenticat_usuario_d26af5_idx'), models.Index(fields=['creado_en'], name='authenticat_creado__b16736_idx')],
            },
        ),
    ]
